// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc2016.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc2016.Robot;

/**
 *
 */
public class SetDriveSpeeds extends Command {
    private double max_vel;
    private double max_accel;

    public SetDriveSpeeds(double max_vel, double max_accel) {
        this.max_vel = max_vel;
        this.max_accel = max_accel;
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
        Robot.driveTrainSRX.setDriveSpeed(max_vel, max_accel);
        Robot.gameTimerStart();
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return true;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    }
}
